### ISSUE TITLE
Crash with vanilla furnace

### ISSUE THREAD

**Issue by Tsunayoshi** [GotoLink/LevelUp#5]
Hey, I am trying out LevelUp for my private Modpack but actually I am getting an "Internal Server Error" if I access a vanilla furnace (slab furnace and electrical furnaces are fine).

Failed to handle packet for /xxx.xxx.xxx.xxx:64168
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[jd.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.inventory.ContainerFurnace.field_75158_e from class assets.levelup.FMLEventHandler
        at assets.levelup.FMLEventHandler.onPlayerUpdate(FMLEventHandler.java:60) ~[FMLEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_367_FMLEventHandler_onPlayerUpdate_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
        ... 10 more

There is no Crashlog, this is from the server console.

Edit: Running forge-1.7.10-10.13.2.1352

**Comment by GotoLink** [comment]
Which version of the mod ?
Latest version (0.10) for 1.7.10 should work.

**Comment by Tsunayoshi** [comment]
(Yeah with LevelUp!-0.10(1.7.10).jar)
I have found the problem! It was my bad. The downloaded file was a .jar.zip after a rename to .jar it works now!
Sorry!!!
